version: '3.3'

services:
  #service 1: definition of mysql database
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=DockerMySQLPassword
      - MYSQL_USER=DockerMySQLUsername
      - MYSQL_PASSWORD=DockerMySQLPassword
      - MYSQL_DATABASE=portfolio
    command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION" --default-authentication-plugin=mysql_native_password
    ports:
      - "33061:3306"
    restart: always

volumes:
  mysql_data:
