# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - develop
  pull_request:
    branches: [ '*' ]
    types: [opened, synchronize, reopened]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  check_run:
    types: [ rerequested, completed ]
  branch_protection_rule:
    types: [ created, deleted ]
  check_suite:
    types: [ completed ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: DockerMySQLPassword
          MYSQL_DATABASE: portfolio
          MYSQL_USER: DockerMySQLUsername
          MYSQL_PASSWORD: DockerMySQLPassword
        ports:
          - "33061:3306"
      zookeeper:
        image: confluentinc/cp-zookeeper:7.0.1
        env:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000
      broker:
        image: confluentinc/cp-kafka:7.0.1
        ports:
          # To learn about configuring Kafka for access across networks see
          # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
          - "9092:9092"
        env:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Set up java version
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Runs build
      - name: Run build
        run: mvn -B package --file pom.xml
